export const runtimeFeatures = [
  {
    id: "semantic",
    number: "01",
    step: "See",
    verb: "Semantic documents",
    capability: "Semantic documents",
    persona: "The observer",
    system: "Perception",
    title: "See what the page means.",
    description:
      "A checkout says “Continue.” Spine reads its name, role, and enabled state, giving your agent a target it can understand.",
    notation: "page → meaning",
    beforeLabel: "Contact page",
    before: "Continue",
    afterLabel: "Spine reads",
    after: "button · enabled",
    caption: "A visible control becomes a meaningful target.",
    illustration:
      "The observer: an engraved eye studies the Continue button on an example Contact page. The reading identifies its name as Continue, its role as button, and its state as enabled.",
  },
  {
    id: "action",
    number: "02",
    step: "Act",
    verb: "Verified actions",
    capability: "Verified actions",
    persona: "The operator",
    system: "Action & feedback",
    title: "Act. Then check the result.",
    description:
      "The agent clicks Continue. Spine lets the page settle and returns the observed result: the checkout has reached Delivery.",
    notation: "intent → evidence",
    beforeLabel: "Action",
    before: "Click Continue",
    afterLabel: "Observed result",
    after: "Delivery loaded",
    caption: "The action is complete when its result is observed.",
    illustration:
      "The operator: an anatomical hand reaches a Continue control. An outward action path and a returning observation path form a feedback loop. The example moves from Contact to the observed Delivery page.",
  },
  {
    id: "session",
    number: "03",
    step: "Keep",
    verb: "Native sessions",
    capability: "Native sessions",
    persona: "The keeper",
    system: "Continuity",
    title: "Carry the context forward.",
    description:
      "Delivery is a new page, but the contact details stay with it. Navigation, cookies, and form state belong to the same session.",
    notation: "one session, many steps",
    beforeLabel: "Contact → Delivery",
    before: "Same session",
    afterLabel: "Email retained",
    after: "alex@example.com",
    caption: "The page changes. The thread stays intact.",
    illustration:
      "The keeper: one continuous mint tract runs through an engraved spinal column, joining Contact and Delivery. Both steps belong to session 01, and the contact email alex@example.com is retained.",
  },
  {
    id: "capability",
    number: "04",
    step: "Choose",
    verb: "Capability maps",
    capability: "Capability maps",
    persona: "The guide",
    system: "Range of action",
    title: "Know which move is possible.",
    description:
      "Delivery needs an address. Spine shows that the field can be filled while Continue is unavailable, so the agent can choose a valid next move.",
    notation: "control → possibility",
    beforeLabel: "Street address",
    before: "Fill available",
    afterLabel: "Continue",
    after: "Click unavailable",
    caption: "The missing address explains the unavailable action.",
    illustration:
      "The guide: an articulated joint is paired with a range-of-action diagram. Its solid branch marks Fill street address as available. Its stopped branch marks Click Continue as unavailable because an address is required.",
  },
  {
    id: "delta",
    number: "05",
    step: "Update",
    verb: "Semantic deltas",
    capability: "Semantic deltas",
    persona: "The messenger",
    system: "Changed state",
    title: "Notice exactly what changed.",
    description:
      "The agent fills “12 Cedar Lane.” Spine reports that Continue changed from disabled to enabled, giving the next action a current view of the page.",
    notation: "state → what changed",
    beforeLabel: "Continue before",
    before: "disabled",
    afterLabel: "Continue after",
    after: "enabled",
    caption: "One field filled. One changed state to carry forward.",
    illustration:
      "The messenger: a branching neuron carries a signal to a receiving cell. A before-and-after state diagram highlights the Continue button changing from disabled to enabled after Street address is filled with 12 Cedar Lane.",
  },
] as const;
